
export const APP_BOOT = 'APP_BOOT';

export const ADD_BATTLE_WON_EVENTS = 'ADD_BATTLE_WON_EVENTS';
export const ADD_BATTLE_CREATED_EVENTS = 'ADD_BATTLE_CREATED_EVENTS';
export const ADD_BATTLE_JOINED_EVENTS = 'ADD_BATTLE_JOINED_EVENTS';
export const ADD_BATTLE_COMMITMENT_SENT_EVENTS = 'ADD_BATTLE_COMMITMENT_SENT_EVENTS';
export const ADD_BATTLE_COMMITMENT_RESOLVED_EVENTS = 'ADD_BATTLE_COMMITMENT_RESOLVED_EVENTS';
export const ADD_ITEM_EVENTS = 'ADD_ITEM_EVENTS';
export const ADD_CONTRACTS = 'ADD_CONTRACTS';
export const ADD_PLAYER_EVENTS = 'ADD_PLAYER_EVENTS';
export const ADD_ACCOUNT_CREDENTIALS = 'ADD_ACCOUNT_CREDENTIALS';

export const GAME_JOIN = 'GAME_JOIN';
export const GAME_LOOT = 'GAME_LOOT';
export const CREATE_BATTLE = 'CREATE_BATTLE';
export const JOIN_BATTLE = 'JOIN_BATTLE';
export const SUBMIT_BATTLE_COMMITMENT = 'SUBMIT_BATTLE_COMMITMENT';
export const SUBMIT_BATTLE_COMMITMENT_RESOLUTION = 'SUBMIT_BATTLE_COMMITMENT_RESOLUTION';